INSERT INTO polls_states VALUES ('AS', 'Aguascalientes', 'aguascalientes');
INSERT INTO polls_states VALUES ('BC', 'Baja California', 'baja-california');
INSERT INTO polls_states VALUES ('BS', 'Baja California Sur', 'baja-california-sur');
INSERT INTO polls_states VALUES ('CC', 'Campeche', 'campeche');
INSERT INTO polls_states VALUES ('CS', 'Chiapas', 'chiapas');
INSERT INTO polls_states VALUES ('CH', 'Chihuahua', 'chihuahua');
INSERT INTO polls_states VALUES ('CL', 'Coahuila', 'coahuila');
INSERT INTO polls_states VALUES ('CM', 'Colima', 'colima');
INSERT INTO polls_states VALUES ('DF', 'Ciudad de México', 'ciudad-de-mexico');
INSERT INTO polls_states VALUES ('DG', 'Durango', 'durango');
INSERT INTO polls_states VALUES ('GT', 'Guanajuato', 'guanajuato');
INSERT INTO polls_states VALUES ('GR', 'Guerrero', 'guerrero');
INSERT INTO polls_states VALUES ('HG', 'Hidalgo', 'hidalgo');
INSERT INTO polls_states VALUES ('JC', 'Jalisco', 'jalisco');
INSERT INTO polls_states VALUES ('MC', 'Estado de México', 'estado-de-mexico');
INSERT INTO polls_states VALUES ('MN', 'Michoacán', 'michoacan');
INSERT INTO polls_states VALUES ('MS', 'Morelos', 'morelos');
INSERT INTO polls_states VALUES ('NT', 'Nayarit', 'nayarit');
INSERT INTO polls_states VALUES ('NL', 'Nuevo León', 'nuevo-leon');
INSERT INTO polls_states VALUES ('OC', 'Oaxaca', 'oaxaca');
INSERT INTO polls_states VALUES ('PL', 'Puebla', 'puebla');
INSERT INTO polls_states VALUES ('QO', 'Querétaro', 'queretaro');
INSERT INTO polls_states VALUES ('QR', 'Quintana Roo', 'quintana-roo');
INSERT INTO polls_states VALUES ('SP', 'San Luis Potosí', 'san-luis-potosi');
INSERT INTO polls_states VALUES ('SL', 'Sinaloa', 'sinaloa');
INSERT INTO polls_states VALUES ('SR', 'Sonora', 'sonora');
INSERT INTO polls_states VALUES ('TC', 'Tabasco', 'tabasco');
INSERT INTO polls_states VALUES ('TS', 'Tamaulipas', 'tamaulipas');
INSERT INTO polls_states VALUES ('TL', 'Tlaxcala', 'tlaxcala');
INSERT INTO polls_states VALUES ('VZ', 'Veracruz', 'veracruz');
INSERT INTO polls_states VALUES ('YN', 'Yucatán', 'yucatan');
INSERT INTO polls_states VALUES ('ZS', 'Zacatecas', 'zacatecas');