# Generated by Django 2.1.3 on 2018-11-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id_article', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200)),
                ('authors', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id_branch', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.TextField(max_length=200)),
                ('direction', models.TextField(max_length=200)),
                ('id_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id_group', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('members', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id_institution', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Investigator',
            fields=[
                ('id_investigator', models.AutoField(primary_key=True, serialize=False)),
                ('id_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
                ('birthdate', models.DateTimeField(verbose_name='Fecha de nacimiento')),
                ('is_admin', models.BooleanField(default=False)),
                ('mail', models.EmailField(max_length=200)),
                ('phone_number', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('id_investigator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Investigator')),
                ('id_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person')),
            ],
        ),
        migrations.AddField(
            model_name='investigator',
            name='id_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Person'),
        ),
        migrations.AddField(
            model_name='branch',
            name='id_institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Institution'),
        ),
    ]
